import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { randomUUID } from 'node:crypto'
import { dirname, isAbsolute, join, relative } from 'node:path'
import process from 'node:process'
import semver from 'semver'
import { parse as parseYaml, stringify } from 'yaml'
import { runPnpm } from './plugin-management.js'

export const DSH_PACKAGE_NAME = '@deepseek-ai/dsh'
export const DSH_RUNTIME_DIRECTORY = 'dsh-runtime'
export const DSH_DESKTOP_RUNTIME_DIRECTORY = '.dsh-desktop-runtime'
export const DSH_ALLOWED_BUILD_PACKAGES = [
  '@deepseek-ai/dsh-subprocess-local',
  'koffi',
  'node-pty',
]
export const DSH_IGNORED_BUILD_PACKAGES = ['@google/genai', 'protobufjs']
// dsh-subprocess-local's postinstall only restores the executable bit of a
// POSIX node-pty helper. Windows has no such helper and its chmod-only script
// trips Electron's embedded pnpm lifecycle runner, so native Windows setup
// needs only the actual node-pty and koffi rebuilds.
const DSH_REBUILD_BUILD_PACKAGES = process.platform === 'win32'
  ? DSH_ALLOWED_BUILD_PACKAGES.filter(packageName => packageName !== '@deepseek-ai/dsh-subprocess-local')
  : DSH_ALLOWED_BUILD_PACKAGES

const REGISTRY_INTEGRITY = /^sha(?:256|384|512)-[A-Za-z0-9+/]+={0,2}$/

/**
 * Keep immutable managed releases outside Electron's Roaming user-data tree.
 * Packaged Windows hosts can virtualize AppData\Roaming; absolute junctions
 * generated by pnpm/DSH then point at the logical alias and become dangling
 * when followed by a child without the same package identity. A user-profile
 * sibling is outside both Roaming and Local package virtualization, so the
 * desktop process, maintenance tools, and independently launched DSH children
 * all resolve one physical tree.
 */
export function resolveManagedDshRuntimeRoot({ userProfile = process.env.USERPROFILE, userData } = {}) {
  if (typeof userProfile === 'string' && userProfile.trim() !== '' && isAbsolute(userProfile)) {
    return join(userProfile, DSH_DESKTOP_RUNTIME_DIRECTORY)
  }
  if (typeof userData === 'string' && userData.trim() !== '' && isAbsolute(userData)) {
    return join(userData, DSH_RUNTIME_DIRECTORY)
  }
  throw new TypeError('A stable desktop runtime data root is required')
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

function writeJsonAtomic(path, value) {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 })
  const temporary = `${path}.tmp-${String(process.pid)}-${randomUUID()}`
  try {
    writeFileSync(temporary, `${JSON.stringify(value, undefined, 2)}\n`, { mode: 0o600, flag: 'wx' })
    renameSync(temporary, path)
  } catch (error) {
    const failure = error instanceof Error ? error : new Error(`Atomic JSON write failed: ${String(error)}`, { cause: error })
    try {
      rmSync(temporary, { force: true, maxRetries: 3, retryDelay: 100 })
    } catch (cleanupError) {
      failure.cleanupError = cleanupError
    }
    throw failure
  }
}

function normalizedVersion(value) {
  if (typeof value !== 'string' || semver.valid(value) !== value) throw new Error('Invalid DSH version')
  return value
}

function normalizedRegistryIntegrity(value) {
  if (typeof value !== 'string' || !REGISTRY_INTEGRITY.test(value)) throw new Error('Invalid DSH package integrity')
  return value
}

function verifiedIntegrityOrThrow(directory, version, expectedIntegrity) {
  const actual = readInstalledIntegrity(directory, version)
  if (expectedIntegrity !== undefined && actual === undefined) {
    const error = new Error(`DSH ${version} package integrity is missing from the lockfile`)
    error.code = 'ERR_DSH_INTEGRITY_UNVERIFIED'
    throw error
  }
  if (expectedIntegrity !== undefined && actual !== expectedIntegrity) {
    const error = new Error(`DSH ${version} package integrity does not match the resolved dist-tag`)
    error.code = 'ERR_DSH_INTEGRITY_MISMATCH'
    throw error
  }
  return actual
}

function abortReason(signal) {
  return signal?.reason instanceof Error ? signal.reason : new Error('DSH runtime operation aborted')
}

function hiddenProcessOptions(hiddenChildProcess) {
  return typeof hiddenChildProcess === 'string' && hiddenChildProcess.trim() !== ''
    ? { hiddenChildProcess }
    : {}
}

function throwIfAborted(signal) {
  if (signal?.aborted) throw abortReason(signal)
}

function errorText(error, seen = new Set()) {
  if (error === undefined || error === null) return ''
  if (typeof error !== 'object') return String(error)
  if (seen.has(error)) return ''
  seen.add(error)
  const parts = []
  if (typeof error.code === 'string') parts.push(error.code)
  if (typeof error.message === 'string') parts.push(error.message)
  if (Array.isArray(error.errors)) {
    for (const child of error.errors) parts.push(errorText(child, seen))
  }
  if (error.cause !== undefined) parts.push(errorText(error.cause, seen))
  return parts.filter(Boolean).join('\n')
}

function isMissingStableDistTag(error, packageName, channel) {
  if (channel !== 'stable') return false
  const detail = errorText(error)
  return detail.includes('ERR_PNPM_PACKAGE_NOT_FOUND') && detail.includes(`${packageName}@${channel}`)
}

function packageManifestPath(directory) {
  return join(directory, 'node_modules', '@deepseek-ai', 'dsh', 'package.json')
}

function isWithin(root, target) {
  const path = relative(root, target)
  return path === '' || (!path.startsWith('..') && !isAbsolute(path))
}

export function inspectDshInstallation({ manifestPath, source }) {
  const manifest = readJson(manifestPath)
  if (manifest.name !== DSH_PACKAGE_NAME) throw new Error('Managed package is not @deepseek-ai/dsh')
  const version = normalizedVersion(manifest.version)
  const entry = join(dirname(manifestPath), 'lib', 'bin.js')
  if (!statSync(entry).isFile()) throw new Error('DSH entry point is missing')
  return { source, version, manifestPath, entry }
}

function managedVersionDirectory(runtimeRoot, version) {
  return join(runtimeRoot, 'versions', normalizedVersion(version))
}

function inspectManagedVersion(runtimeRoot, version) {
  const versionsRoot = join(runtimeRoot, 'versions')
  const directory = managedVersionDirectory(runtimeRoot, version)
  if (!lstatSync(directory).isDirectory()) throw new Error('Managed DSH version is not a directory')
  const realDirectory = realpathSync(directory)
  if (!isWithin(realpathSync(versionsRoot), realDirectory)) throw new Error('Managed DSH version escapes the runtime directory')
  const installation = inspectDshInstallation({ manifestPath: packageManifestPath(directory), source: 'managed' })
  if (installation.version !== version) throw new Error('Managed DSH version does not match its activation record')
  if (!isWithin(realDirectory, realpathSync(installation.entry))) throw new Error('Managed DSH entry escapes its version directory')
  return { ...installation, directory }
}

export function readActiveDshRuntime({ runtimeRoot, bundledManifestPath }) {
  const bundled = inspectDshInstallation({ manifestPath: bundledManifestPath, source: 'bundled' })
  const activePath = join(runtimeRoot, 'active.json')
  if (!existsSync(activePath)) return { ...bundled, bundled }
  try {
    const active = readJson(activePath)
    return { ...inspectManagedVersion(runtimeRoot, normalizedVersion(active.version)), bundled }
  } catch (error) {
    try {
      rmSync(activePath, { force: true })
    } catch {
      // A read-only corrupt activation record is ignored; the bundled runtime still starts.
    }
    return {
      ...bundled,
      bundled,
      managedError: error instanceof Error ? error.message : String(error),
    }
  }
}

export function parseDshRegistryVersion(output) {
  const candidates = [String(output).trim(), ...String(output).split(/\r?\n/).map(line => line.trim()).reverse()]
  for (const candidate of candidates) {
    if (candidate === '') continue
    try {
      const value = JSON.parse(candidate)
      const version = typeof value === 'string' ? value : value?.version
      if (typeof version === 'string' && semver.valid(version) === version) return version
    } catch {
      // pnpm may print a warning beside the JSON response; inspect individual lines next.
    }
  }
  throw new Error('The npm registry returned an invalid DSH version')
}

function jsonCandidates(output) {
  const text = String(output ?? '').trim()
  const candidates = [text, ...text.split(/\r?\n/).map(line => line.trim()).reverse()]
  // Node may print warnings such as "[UNDICI-EHPA]" before pnpm's JSON.
  // Taking the first bracket therefore selects the warning instead of the
  // JSON document. Try every plausible JSON start and its matching final
  // delimiter so registry resolution remains stable across Node/Electron.
  for (const match of text.matchAll(/[\[{]/g)) {
    const start = match.index ?? -1
    if (start < 0) continue
    const opener = text[start]
    const closer = opener === '{' ? '}' : ']'
    const end = text.lastIndexOf(closer)
    if (end > start) candidates.push(text.slice(start, end + 1))
  }
  return [...new Set(candidates.filter(candidate => candidate !== ''))]
}

function releaseFromRegistryValue(value, channel) {
  if (Array.isArray(value)) {
    for (const entry of value) {
      const release = releaseFromRegistryValue(entry, channel)
      if (release !== undefined) return release
    }
    return undefined
  }
  if (value === null || typeof value !== 'object') return undefined

  const tags = value['dist-tags'] ?? value.distTags
  const taggedVersion = typeof tags?.[channel] === 'string' ? tags[channel] : undefined
  const version = value.version ?? value[channel] ?? taggedVersion
  const versionRecord = taggedVersion === undefined ? undefined : value.versions?.[taggedVersion]
  const dist = value.dist ?? versionRecord?.dist
  const integrity = value.integrity
    ?? value['dist.integrity']
    ?? value.distIntegrity
    ?? dist?.integrity
    ?? value.resolution?.integrity
    ?? versionRecord?.resolution?.integrity
  if (typeof version !== 'string' || semver.valid(version) !== version || typeof integrity !== 'string') return undefined
  return {
    channel,
    version: normalizedVersion(version),
    integrity: normalizedRegistryIntegrity(integrity),
  }
}

export function parseDshRegistryRelease(output, channel = 'stable') {
  if (!['stable', 'next'].includes(channel)) throw new Error('Invalid DSH release channel')
  for (const candidate of jsonCandidates(output)) {
    try {
      const release = releaseFromRegistryValue(JSON.parse(candidate), channel)
      if (release !== undefined) return release
    } catch {
      // Inspect the next JSON fragment. pnpm may prefix the response with a warning.
    }
  }
  throw new Error(`The npm registry returned no exact ${channel} DSH version and integrity`)
}

export const parseDshDistTag = parseDshRegistryRelease

export async function resolveDshDistTag({
  channel,
  packageName = DSH_PACKAGE_NAME,
  runtimeRoot,
  pnpmEntry,
  execPath,
  env,
  signal,
  onOutput,
  hiddenChildProcess,
  runPnpmImpl = runPnpm,
}) {
  if (!['stable', 'next'].includes(channel)) throw new Error('Invalid DSH release channel')
  throwIfAborted(signal)
  if (runtimeRoot !== undefined) mkdirSync(runtimeRoot, { recursive: true, mode: 0o700 })
  throwIfAborted(signal)
  let result
  try {
    result = await runPnpmImpl({
      args: ['view', `${packageName}@${channel}`, 'version', 'dist.integrity', '--json'],
      env,
      execPath,
      ...hiddenProcessOptions(hiddenChildProcess),
      onOutput,
      pnpmEntry,
      profileDir: runtimeRoot,
      signal,
    })
  } catch (error) {
    // Some registries publish the package without a literal `stable` dist-tag.
    // Resolve the latest published package metadata instead of failing the
    // first-run candidate flow. The exact version and SRI are still carried
    // into installDshVersion, so the candidate remains reproducible.
    if (!isMissingStableDistTag(error, packageName, channel)) throw error
    throwIfAborted(signal)
    result = await runPnpmImpl({
      args: ['view', packageName, 'version', 'dist.integrity', '--json'],
      env,
      execPath,
      ...hiddenProcessOptions(hiddenChildProcess),
      onOutput,
      pnpmEntry,
      profileDir: runtimeRoot,
      signal,
    })
  }
  throwIfAborted(signal)
  return {
    packageName,
    distTag: channel,
    ...parseDshRegistryRelease(result?.output ?? result?.stdout ?? result, channel),
  }
}

export async function checkForDshUpdate({
  currentVersion,
  channel,
  runtimeRoot,
  pnpmEntry,
  execPath,
  env,
  signal,
  onOutput,
  hiddenChildProcess,
  runPnpmImpl = runPnpm,
}) {
  const current = normalizedVersion(currentVersion)
  throwIfAborted(signal)
  mkdirSync(runtimeRoot, { recursive: true, mode: 0o700 })
  throwIfAborted(signal)
  if (channel !== undefined) {
    const latest = await resolveDshDistTag({
      channel,
      runtimeRoot,
      pnpmEntry,
      execPath,
      env,
      signal,
      onOutput,
      ...hiddenProcessOptions(hiddenChildProcess),
      runPnpmImpl,
    })
    return {
      currentVersion: current,
      latestVersion: latest.version,
      latestIntegrity: latest.integrity,
      channel: latest.channel,
      available: semver.gt(latest.version, current),
    }
  }
  const result = await runPnpmImpl({
    args: ['view', DSH_PACKAGE_NAME, 'version', '--json'],
    env,
    execPath,
    ...hiddenProcessOptions(hiddenChildProcess),
    onOutput,
    pnpmEntry,
    profileDir: runtimeRoot,
    signal,
  })
  throwIfAborted(signal)
  const latestVersion = parseDshRegistryVersion(result.output)
  return {
    currentVersion: current,
    latestVersion,
    available: semver.gt(latestVersion, current),
  }
}

export async function installDshVersion({
  version,
  integrity,
  runtimeRoot,
  pnpmEntry,
  execPath,
  env,
  signal,
  onOutput,
  hiddenChildProcess,
  runPnpmImpl = runPnpm,
  removeImpl = rmSync,
}) {
  const normalized = normalizedVersion(version)
  const expectedIntegrity = integrity === undefined ? undefined : normalizedRegistryIntegrity(integrity)
  const versionsRoot = join(runtimeRoot, 'versions')
  const target = managedVersionDirectory(runtimeRoot, normalized)
  throwIfAborted(signal)
  mkdirSync(versionsRoot, { recursive: true, mode: 0o700 })

  try {
    // Staging is deliberately read-only with respect to activation. A verified
    // version is only a candidate until the owner explicitly publishes it.
    const existing = inspectManagedVersion(runtimeRoot, normalized)
    const existingIntegrity = verifiedIntegrityOrThrow(existing.directory, normalized, expectedIntegrity)
    return { ...existing, ...(existingIntegrity === undefined ? {} : { integrity: existingIntegrity }), reused: true }
  } catch (error) {
    if (error?.code === 'ERR_DSH_INTEGRITY_UNVERIFIED' || error?.code === 'ERR_DSH_INTEGRITY_MISMATCH') throw error
    // A partial prior install is app-owned and will be replaced after a fresh verified install.
  }

  const staging = join(runtimeRoot, `staging-${String(process.pid)}-${String(Date.now())}`)
  let movedToTarget = false
  try {
    throwIfAborted(signal)
    mkdirSync(staging, { recursive: false, mode: 0o700 })
    throwIfAborted(signal)
    writeJsonAtomic(join(staging, 'package.json'), {
      name: 'dsh-desktop-managed-runtime',
      private: true,
      version: '0.0.0',
      dependencies: {},
    })
    throwIfAborted(signal)
    writeFileSync(join(staging, 'pnpm-workspace.yaml'), stringify({
      packages: ['.'],
      allowBuilds: {
        ...Object.fromEntries(DSH_ALLOWED_BUILD_PACKAGES.map(packageName => [packageName, true])),
        ...Object.fromEntries(DSH_IGNORED_BUILD_PACKAGES.map(packageName => [packageName, false])),
      },
    }), { mode: 0o600 })

    throwIfAborted(signal)
    // Keep dependency resolution separate from lifecycle scripts. Electron's
    // embedded pnpm can otherwise attach a non-readable inherited stream while
    // running postinstall hooks ("readStream must be readable"). Dependency
    // installation remains script-free, then only the explicit, approved
    // native build packages are rebuilt through the same owned pipe runner.
    await runPnpmImpl({
      args: [
        'add',
        // pnpm's default isolated linker writes absolute symlinks from
        // node_modules into the temporary staging directory. The candidate
        // is renamed to its final version directory after verification, so
        // those links would point back to a path that no longer exists on
        // Windows. Hoisted layout keeps the managed runtime relocatable.
        '--node-linker=hoisted',
        '--save-prod',
        '--save-exact',
        '--ignore-scripts',
        '--reporter',
        'append-only',
        `${DSH_PACKAGE_NAME}@${normalized}`,
      ],
      env,
      execPath,
      ...hiddenProcessOptions(hiddenChildProcess),
      onOutput,
      pnpmEntry,
      profileDir: staging,
      signal,
    })
    throwIfAborted(signal)
    await runPnpmImpl({
      args: [
        'rebuild',
        ...DSH_REBUILD_BUILD_PACKAGES,
        '--reporter',
        'append-only',
      ],
      env,
      execPath,
      ...hiddenProcessOptions(hiddenChildProcess),
      onOutput,
      pnpmEntry,
      profileDir: staging,
      signal,
    })
    // A canceled pnpm operation may have produced a complete candidate. Do not
    // publish or replace anything after that cancellation boundary.
    throwIfAborted(signal)
    const installed = inspectDshInstallation({ manifestPath: packageManifestPath(staging), source: 'managed' })
    if (installed.version !== normalized) throw new Error(`Expected DSH ${normalized}, installed ${installed.version}`)
    const lockIntegrity = readInstalledIntegrity(staging, normalized)
    const verifiedIntegrity = expectedIntegrity === undefined
      ? lockIntegrity
      : verifiedIntegrityOrThrow(staging, normalized, expectedIntegrity)
    throwIfAborted(signal)
    if (existsSync(target)) {
      throwIfAborted(signal)
      removeImpl(target, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 })
    }
    throwIfAborted(signal)
    renameSync(staging, target)
    movedToTarget = true
    // Verify the moved directory, but never activate it here. The caller owns
    // the readiness gate and the active.json publication boundary.
    const staged = inspectManagedVersion(runtimeRoot, normalized)
    return {
      ...staged,
      ...(verifiedIntegrity === undefined ? {} : { integrity: verifiedIntegrity }),
      reused: false,
    }
  } catch (error) {
    // Cleanup is limited to this transaction's staging/candidate directory. It
    // must never touch active.json, including when the signal is already aborted.
    const failure = error instanceof Error ? error : new Error(`DSH installation failed: ${String(error)}`, { cause: error })
    const cleanupErrors = []
    try {
      removeImpl(staging, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 })
    } catch (cleanupError) {
      cleanupErrors.push(cleanupError)
    }
    if (movedToTarget) {
      try {
        removeImpl(target, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 })
      } catch (cleanupError) {
        cleanupErrors.push(cleanupError)
      }
    }
    if (cleanupErrors.length > 0) {
      failure.cleanupError = cleanupErrors.length === 1
        ? cleanupErrors[0]
        : new AggregateError(cleanupErrors, 'DSH installation cleanup failed')
    }
    throw failure
  }
}

function readInstalledIntegrity(directory, version) {
  const lockPath = join(directory, 'pnpm-lock.yaml')
  if (!existsSync(lockPath)) return undefined
  try {
    const lock = parseYaml(readFileSync(lockPath, 'utf8'))
    const packages = lock?.packages ?? {}
    const record = Object.entries(packages).find(([key]) => key === `${DSH_PACKAGE_NAME}@${version}` || key.startsWith(`${DSH_PACKAGE_NAME}@${version}(`))?.[1]
    const integrity = record?.resolution?.integrity
    return integrity === undefined ? undefined : normalizedRegistryIntegrity(integrity)
  } catch (error) {
    throw new Error(`Unable to inspect the installed DSH package integrity: ${error instanceof Error ? error.message : String(error)}`, { cause: error })
  }
}

export function activateManagedDsh(runtimeRoot, version, { signal } = {}) {
  const normalized = normalizedVersion(version)
  throwIfAborted(signal)
  const managed = inspectManagedVersion(runtimeRoot, normalized)
  throwIfAborted(signal)
  mkdirSync(runtimeRoot, { recursive: true, mode: 0o700 })
  throwIfAborted(signal)
  writeJsonAtomic(join(runtimeRoot, 'active.json'), { version: normalized })
  return managed
}

export function deactivateManagedDsh(runtimeRoot, { signal } = {}) {
  throwIfAborted(signal)
  rmSync(join(runtimeRoot, 'active.json'), { force: true })
}
